# Site settings
name:        "Marek Vavrusa"
title:       "Marek Vavrusa"
email:       marek@vavrusa.com
author:      "Marek Vavrusa"
description: "I'm a traveler in time and space."
baseurl:     ""
url:         "https://marek.vavrusa.com"

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: marek-vavrusa

# Social icons
show_social_icons: true
github_username: vavrusa
stackoverflow_id: 4591872/marek-vavrusa
twitter_username: vavrusam
google_plus_id:
linkedin_username: vavrusam
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data', 'strikethrough', 'footnotes']
permalink:    pretty
paginate:     3
sass:
  compressed: true
